version: "3.8"
services:
  db:
    image: postgres
    container_name: team2 
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    # volumes:
    #   - example_db:
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
# volumes:
#   example_db:
